const api = '/api/admin';
const categoryLabels = {metadata:'元数据',region:'地区总览',champions:'英雄',stories:'人物故事',places:'地点',factions:'派系',timeline:'时间线',relationships:'关系网',sources:'官方来源'};
let nodes = [], loreRecords = [], loreSummary = null, entityCatalog = {}, officialRecords = [], currentView = 'nodes', currentCategory = 'champions', editingLoreId = null;

const $ = selector => document.querySelector(selector);
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className=`toast show${error?' error':''}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.className='toast',2800);}
async function request(url,options={}){const response=await fetch(url,{headers:{'Content-Type':'application/json'},...options});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.detail||`请求失败 (${response.status})`);}return response.status===204?null:response.json();}
function escapeHtml(value=''){const el=document.createElement('div');el.textContent=String(value);return el.innerHTML;}

function setView(view){currentView=view;$('#nodesView').hidden=view!=='nodes';$('#loreView').hidden=view!=='lore';document.querySelectorAll('.console-tab').forEach(button=>button.classList.toggle('active',button.dataset.view===view));$('#primaryAction').textContent=view==='nodes'?'＋ 新建节点':'＋ 新建资料';if(view==='lore')loadLore();else loadNodes();}
document.querySelectorAll('.console-tab').forEach(button=>button.onclick=()=>setView(button.dataset.view));

function renderStatus(status){const active=status.active_node;$('#signal').classList.toggle('on',Boolean(active));$('#statusTitle').textContent=active?`${active.name} 正在工作`:'当前没有启用节点';$('#statusText').textContent=active?`${active.model} · ${active.base_url}`:'游戏将使用本地规则文案；开启节点后由后端调用 AI。';}
function renderNodes(){
  $('#nodeCount').textContent=nodes.length;$('#emptyState').hidden=nodes.length!==0;$('#nodeGrid').innerHTML='';
  for(const node of nodes){const card=document.createElement('article');card.className=`card${node.enabled?' active':''}`;card.innerHTML=`<div class="card-top"><div><h3>${escapeHtml(node.name)}</h3><span class="provider">${escapeHtml(node.provider)}</span></div><button class="switch ${node.enabled?'on':''}" aria-label="${node.enabled?'关闭':'启用'}节点"></button></div><div class="details"><div class="detail"><span>模型</span><span>${escapeHtml(node.model)}</span></div><div class="detail"><span>地址</span><span title="${escapeHtml(node.base_url)}">${escapeHtml(node.base_url)}</span></div><div class="detail"><span>密钥</span><span>${escapeHtml(node.key_mask)}</span></div></div><div class="card-actions"><button class="ghost test">测试连接</button><button class="ghost edit">编辑</button><button class="danger remove">删除</button></div>`;card.querySelector('.switch').onclick=()=>toggleNode(node);card.querySelector('.test').onclick=e=>testNode(node,e.currentTarget);card.querySelector('.edit').onclick=()=>openNodeDialog(node);card.querySelector('.remove').onclick=()=>removeNode(node);$('#nodeGrid').append(card);}
}
async function loadNodes(){try{const data=await request(`${api}/ai-nodes`);nodes=data.nodes;renderNodes();renderStatus(data.status);}catch(e){toast(e.message,true);}}
async function toggleNode(node){try{const data=await request(`${api}/ai-nodes/${node.id}/toggle`,{method:'POST',body:JSON.stringify({enabled:!node.enabled})});nodes=data.nodes;renderNodes();renderStatus(data.status);toast(data.node.enabled?`已启用 ${node.name}`:`已关闭 ${node.name}`);}catch(e){toast(e.message,true);}}
async function testNode(node,button){const old=button.textContent;button.disabled=true;button.textContent='测试中…';try{const data=await request(`${api}/ai-nodes/${node.id}/test`,{method:'POST'});toast(`${node.name}：${data.message}`);}catch(e){toast(e.message,true);}finally{button.disabled=false;button.textContent=old;}}
async function removeNode(node){if(!confirm(`确定删除“${node.name}”吗？`))return;try{await request(`${api}/ai-nodes/${node.id}`,{method:'DELETE'});toast('节点已删除');await loadNodes();}catch(e){toast(e.message,true);}}
function openNodeDialog(node=null){$('#nodeForm').reset();$('#nodeId').value=node?.id||'';$('#dialogTitle').textContent=node?'编辑节点':'新建节点';$('#name').value=node?.name||'';$('#provider').value=node?.provider||'deepseek';$('#model').value=node?.model||'deepseek-v4-flash';$('#baseUrl').value=node?.base_url||'https://api.deepseek.com';$('#apiKey').required=!node;$('#nodeDialog').showModal();}
$('#nodeForm').onsubmit=async event=>{event.preventDefault();const id=$('#nodeId').value;const payload={name:$('#name').value,provider:$('#provider').value,model:$('#model').value,base_url:$('#baseUrl').value,api_key:$('#apiKey').value};$('#saveButton').disabled=true;try{await request(`${api}/ai-nodes${id?'/'+id:''}`,{method:id?'PUT':'POST',body:JSON.stringify(payload)});$('#nodeDialog').close();toast(id?'节点已更新':'节点已保存，默认保持关闭');await loadNodes();}catch(e){toast(e.message,true);}finally{$('#saveButton').disabled=false;}};

function renderCategoryTabs(){const counts=loreSummary?.counts||{};$('#categoryTabs').innerHTML='';for(const [id,label] of Object.entries(categoryLabels)){const button=document.createElement('button');button.className=`category-tab${id===currentCategory?' active':''}`;button.innerHTML=`${label}<b>${counts[id]||0}</b>`;button.onclick=()=>{currentCategory=id;renderCategoryTabs();loadLoreRecords();};$('#categoryTabs').append(button);}}
function loreExcerpt(data){return data.profile||data.preview||data.summary||data.overview||data.current_situation||data.url||data.scope||'结构化世界观资料';}
function loreMeta(record){const d=record.data;if(currentCategory==='champions')return [d.title,d.species,d.status];if(currentCategory==='stories')return [d.author,d.minutes_to_read?`${d.minutes_to_read} 分钟阅读`:'',d.related_characters?.length?`关联 ${d.related_characters.length} 位角色`:''];if(currentCategory==='timeline')return [d.era,d.precision];if(currentCategory==='relationships')return [d.type,d.direction];if(currentCategory==='sources')return [d.type];return [d.type,d.origin].filter(Boolean);}
function renderLore(){
  $('#loreEmpty').hidden=loreRecords.length!==0;
  const officialIds=new Set(officialRecords.filter(item=>item.category===currentCategory).map(item=>item.id));
  LoreVisuals.render({mount:$('#loreGrid'),category:currentCategory,records:loreRecords,catalog:entityCatalog,escape:escapeHtml,excerpt:loreExcerpt,meta:loreMeta,onEdit:openLoreDialog,onDelete:removeLore,onOfficial:openOfficialLore,officialIds});
}
async function loadLore(){try{const [summary,official]=await Promise.all([request(`${api}/lore`),request(`${api}/lore-official`)]);loreSummary=summary;officialRecords=official.records;const total=Object.values(loreSummary.counts).reduce((sum,value)=>sum+value,0);$('#loreTotal').textContent=total;renderCategoryTabs();await loadLoreRecords();}catch(e){toast(e.message,true);}}
async function loadLoreRecords(){try{const query=encodeURIComponent($('#loreSearch').value.trim());const data=await request(`${api}/lore/${currentCategory}?q=${query}`);loreRecords=data.records;if(['relationships','timeline','places'].includes(currentCategory)&&!Object.keys(entityCatalog).length){const groups=await Promise.all(['champions','places','factions','region'].map(category=>request(`${api}/lore/${category}?limit=500`)));entityCatalog=Object.fromEntries(groups.flatMap(group=>group.records).map(record=>[record.id,{name:record.title,image_url:record.data.image_url||'',category:record.category}]));entityCatalog.ionia={name:'艾欧尼亚',image_url:'',category:'region'};}renderLore();}catch(e){toast(e.message,true);}}
function openLoreDialog(record=null){editingLoreId=record?.id||null;$('#loreForm').reset();$('#loreDialogTitle').textContent=record?'查看 / 编辑资料':'新建知识资料';$('#loreCategory').innerHTML=Object.entries(categoryLabels).map(([id,label])=>`<option value="${id}">${label}</option>`).join('');$('#loreCategory').value=record?.category||currentCategory;$('#loreCategory').disabled=Boolean(record);$('#loreId').value=record?.id||'';$('#loreId').readOnly=Boolean(record);$('#loreTitle').value=record?.title||'';$('#loreData').value=JSON.stringify(record?.data||{id:'',summary:'',source_ids:[]},null,2);$('#loreDialog').showModal();}
function htmlText(value=''){const el=document.createElement('div');el.innerHTML=String(value);return el.textContent.trim();}
function officialImage(payload){const image=payload.image||payload.faction?.image||payload.story?.['story-sections']?.[0]?.['background-image']||payload.raw?.story?.['story-sections']?.[0]?.['background-image']||{};const value=image.uri||image.url||image.src||'';return /^https:\/\/(game\.gtimg\.cn|yz\.lol\.qq\.com)\//.test(value)?value:'';}
async function openOfficialLore(record){if(record.category==='stories')return openOfficialStory(record.id,true);try{const data=await request(`${api}/lore-official/${record.category}/${record.id}`),snapshot=data.record,p=snapshot.payload,b=p.biography||{},champion=p.raw?.champion||p.champion||{},faction=p.faction||{},overview=faction.overview||p.overview||{},shortText=b.short_text||htmlText(b.short||champion.biography?.short||overview.short||''),fullText=b.full_text||htmlText(b.full||champion.biography?.full||overview.full||overview.short||''),modules=p.modules||p.raw?.modules||[],image=officialImage(p)||officialImage(champion);$('#officialLoreTitle').textContent=`${p.official_name||champion.name||snapshot.title}${p.official_title||champion.title?` · ${p.official_title||champion.title}`:''}`;$('#officialLoreMeta').textContent=`中文官网原文快照 · ${snapshot.category} · 更新于 ${snapshot.updated_at}`;$('#officialLoreImage').hidden=!image;if(image)$('#officialLoreImage').src=image;$('#officialLoreShort').textContent=shortText;$('#officialLoreFull').textContent=fullText;$('#officialLoreModules').innerHTML=modules.slice(0,30).map(module=>module['story-slug']?`<li><button class="official-story-link" data-story="${escapeHtml(module['story-slug'])}">${escapeHtml(module.title||'中文官网故事')}</button></li>`:`<li>${escapeHtml(module.title||module.name||module.type||module.id||'官网图文模块')}</li>`).join('');$('#officialLoreModules').querySelectorAll('.official-story-link').forEach(button=>button.onclick=()=>openOfficialStory(button.dataset.story));$('#officialLoreSource').href=snapshot.source_url;$('#officialLoreDialog').showModal();}catch(e){toast(e.message,true);}}
async function openOfficialStory(storyId,showDialog=false){try{const data=await request(`${api}/lore-official/stories/${encodeURIComponent(storyId)}`),snapshot=data.record,p=snapshot.payload,image=officialImage(p);$('#officialLoreTitle').textContent=p.title||snapshot.title;$('#officialLoreMeta').textContent=`${p.subtitle||'中文官网故事'} · ${p.minutes_to_read?`${p.minutes_to_read} 分钟阅读 · `:''}中文官网原文快照`;$('#officialLoreImage').hidden=!image;if(image)$('#officialLoreImage').src=image;$('#officialLoreShort').textContent=p.preview||'';$('#officialLoreFull').textContent=p.body_text||'';$('#officialLoreModules').innerHTML=(p.related_characters||[]).map(id=>`<li>相关角色：${escapeHtml(entityCatalog[id]?.name||id)}</li>`).join('');$('#officialLoreSource').href=snapshot.source_url;if(showDialog)$('#officialLoreDialog').showModal();}catch(e){toast(e.message,true);}}
async function removeLore(record){if(!confirm(`确定从数据库删除“${record.title}”吗？该操作会影响事件检索。`))return;try{await request(`${api}/lore/${record.category}/${record.id}`,{method:'DELETE'});toast('知识资料已删除');await loadLore();}catch(e){toast(e.message,true);}}
$('#loreForm').onsubmit=async event=>{event.preventDefault();let data;try{data=JSON.parse($('#loreData').value);}catch{toast('JSON 格式不正确，请检查逗号和引号。',true);return;}const category=$('#loreCategory').value,id=$('#loreId').value.trim(),title=$('#loreTitle').value.trim();const payload=editingLoreId?{title,data}:{id,title,data};$('#loreSaveButton').disabled=true;try{await request(`${api}/lore/${category}${editingLoreId?'/'+editingLoreId:''}`,{method:editingLoreId?'PUT':'POST',body:JSON.stringify(payload)});$('#loreDialog').close();toast('知识资料已保存，事件检索将立即使用');currentCategory=category;await loadLore();}catch(e){toast(e.message,true);}finally{$('#loreSaveButton').disabled=false;}};

let searchTimer;$('#loreSearch').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(loadLoreRecords,260);};
$('#primaryAction').onclick=()=>currentView==='nodes'?openNodeDialog():openLoreDialog();$('#refreshButton').onclick=loadNodes;$('#closeButton').onclick=()=>$('#nodeDialog').close();$('#cancelButton').onclick=()=>$('#nodeDialog').close();$('#loreCloseButton').onclick=()=>$('#loreDialog').close();$('#loreCancelButton').onclick=()=>$('#loreDialog').close();
$('#officialLoreClose').onclick=()=>$('#officialLoreDialog').close();
loadNodes();
